# Generated by Django 3.2.4 on 2021-06-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
