# Generated by Django 3.2.4 on 2021-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210608_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_prize',
            name='bnb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='second_prize',
            name='bnb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='third_prize',
            name='bnb',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
